---
title: "Untitled"
author: "Waseem"
date: "10/17/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r echo=TRUE}
library(jsonlite)
library(sf)
library(ggplot2)
library(tidyverse)

get_taxi_data <- function(tstamp) {
  url_tmp <- paste0("https://api.data.gov.sg/v1/transport/taxi-availability?date_time=",
                    format(tstamp, "%Y-%m-%dT%H:%M:%S"))
  data_tmp <- fromJSON(url_tmp)
  class(data_tmp) <- "taxi_json"
  data_tmp
}

summary.taxi_json <- function(object, ...) {
  cat(paste("Taxi count:", object$features$properties$taxi_count), "\n")
  cat(paste("Actual timestamp:", object$features$properties$timestamp), "\n")
}
as.data.frame.taxi_json <- function(x, row.names = NULL, optional = FALSE, ...){
  t_coords <- as.data.frame(x$features$geometry$coordinates[[1]])
  taxis <- st_as_sf(t_coords, coords=c(1,2))
  st_crs(taxis) <- 4326
  taxis <- st_transform(taxis, 3414)
  taxis
}

pln_areas<- readRDS("data/sg_planning_areas.rds")
dt1<- as.POSIXct("2021-01-10 09:00:00")
wet_day_locs<-get_taxi_data(dt1)
wet_day_sf <- as.data.frame(wet_day_locs)
wet_count <- st_contains(pln_areas, wet_day_sf) %>% 
  sapply( FUN=length)  


dt2 <- as.POSIXct("2021-01-17 09:00:00")
dry_day_locs <- get_taxi_data(dt2)
dry_day_sf <- as.data.frame(dry_day_locs)
dry_count <- st_contains(pln_areas, dry_day_sf) %>% sapply( FUN=length) 

planning_area<-pln_areas$PLN_AREA_N %>% as_tibble()

```
```{r echo = TRUE}

taxi_count<-planning_area %>%
  rename(planning_area = value )%>%
    mutate(wetcount=wet_count)%>%
  mutate(drycount=dry_count)%>%
mutate(planning_area=reorder(planning_area,wetcount))
taxi_count

ggplot()+
  geom_point(data=taxi_count, aes(x= wetcount, y = planning_area), color = "blue" )  +
  geom_segment(data=taxi_count,aes(x=wetcount, xend=drycount, y=planning_area, yend=planning_area) )+
  geom_point(data= taxi_count, aes(x= drycount, y= planning_area), colour="red") +
  ylab("Planning Area") +
  xlab("Taxi Count")+
  theme(axis.text.y=element_text(size=5))+
  annotate("segment",x=150,xend=160,y=5,yend=5,size=0.5)+
  annotate("point",x=150,y=5,colour="blue") +
  annotate("point",x=160,y=5,colour="red") +
  annotate("text", x=c(140,170), y=c(5,5), label=c("Wet Count","Dry Count"),size=2)
```